### ISSUE TITLE
Server crash in magic wand mod

### ISSUE THREAD

**Issue by AndersBillLinden** [AndersBillLinden/minecraft-mods#1]
https://gist.github.com/AndersBillLinden/dc4b576ead6f4f4a64ec

**Comment by AndersBillLinden** [comment]
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2015-12-07 22:05
Description: Ticking entity

java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
    at java.util.LinkedList$ListItr.remove(Unknown Source)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdate(EntityPlayerMP.java:308)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2019)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:724)
    at net.minecraft.world.World.updateEntity(World.java:1984)
    at net.minecraft.world.World.updateEntities(World.java:1813)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:559)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:771)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:675)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:159)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:542)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
    at java.util.LinkedList$ListItr.remove(Unknown Source)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdate(EntityPlayerMP.java:308)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2019)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:724)
    at net.minecraft.world.World.updateEntity(World.java:1984)

-- Entity being ticked --
Details:
    Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
    Entity ID: 224
    Entity Name: Player375
    Entity's Exact location: 466,93, 67,00, -192,94
    Entity's Block location: 466,00,67,00,-193,00 - World: (466,67,-193), Chunk: (at 2,4,15 in 29,-13; contains blocks 464,0,-208 to 479,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Entity's Momentum: 0,00, -0,08, 0,00
    Entity's Rider: ~~ERROR~~ NullPointerException: null
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.updateEntities(World.java:1813)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:559)

-- Affected level --
Details:
    Level name: test
    All players: 1 total; [EntityPlayerMP['Player375'/224, l='test', x=466,93, y=67,00, z=-192,94]]
    Chunk stats: ServerChunkCache: 1135 Drop: 0
    Level seed: -3549691383939950131
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: 366,00,64,00,53,00 - World: (366,64,53), Chunk: (at 14,4,5 in 22,3; contains blocks 352,0,48 to 367,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 935283 game time, 3554 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 6198 (now: false), thunder time: 2062 (now: true)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:771)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:675)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:159)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:542)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.8.8
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_65, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 462438808 bytes (441 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
    JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.18 Powered by Forge 11.14.4.1576 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8.8-11.14.4.1576-1.8.8.jar) 
    UCHIJAAAA   Forge{11.14.4.1576} [Minecraft Forge] (forgeSrc-1.8.8-11.14.4.1576-1.8.8.jar) 
    UCHIJAAAA   magicwandmod{1.0.0} [Magic Wand Mod] (bin) 
    Loaded coremods (and transformers): 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['Player375'/224, l='test', x=466,93, y=67,00, z=-192,94]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```
